const styles = {
  container: {
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    backgroundColor: "#1a1a1a",
    fontFamily: "'Roboto', sans-serif",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "10px 20px",
    color: "white",
    height: "60px",
  },
  headerTitle: {
    fontSize: "20px",
    fontWeight: "bold",
  },
  headerControls: {
    display: "flex",
    alignItems: "center",
    gap: "15px",
  },
  folderUpload: {
    display: "inline-block",
  },
  folderLabel: {
    padding: "8px 16px",
    backgroundColor: "#3B82F6",
    color: "white",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "500",
  },
  controls: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  controlLabel: {
    color: "#cccccc",
    fontSize: "14px",
    display: "flex",
    alignItems: "center",
  },
  headerFileList: {
    display: "flex",
    gap: "10px",
    overflowX: "auto",
    maxWidth: "400px",
  },
  headerFileItem: (isSelected) => ({
    padding: "6px 12px",
    backgroundColor: isSelected ? "#3B82F6" : "#2D3748",
    color: "white",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "12px",
    whiteSpace: "nowrap",
  }),
  contentArea: {
    display: "flex",
    flex: 1,
    overflow: "hidden",
  },
  mainContent: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    padding: "20px",
    overflow: "auto",
  },
  visualization: {
    flex: 1,
    position: "relative",
    backgroundColor: "#000000",
    borderRadius: "8px",
    overflow: "hidden",
    marginBottom: "20px",
  },
  canvasContainer: {
    width: "100%",
    height: "100%",
    position: "relative",
  },
  loading: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    color: "white",
    fontSize: "16px",
  },
  noFileMessage: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    color: "#cccccc",
    fontSize: "16px",
    textAlign: "center",
  },
  gradientScale: {
    position: "absolute",
    bottom: "20px",
    left: "20px",
    zIndex: 10,
  },
  thumbnailsContainer: {
    display: "flex",
    gap: "15px",
    overflowX: "auto",
    padding: "10px 0",
  },
  thumbnailItem: (isSelected) => ({
    width: "100px",
    height: "100px",
    position: "relative",
    border: isSelected ? "2px solid #3B82F6" : "2px solid #404040",
    borderRadius: "6px",
    cursor: "pointer",
    overflow: "hidden",
  }),
  thumbnailLabel: {
    position: "absolute",
    bottom: "0",
    left: "0",
    right: "0",
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    color: "white",
    fontSize: "10px",
    padding: "4px",
    textAlign: "center",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
};

///Gunning Screen styles
export const panelStyles = {
  sectionTitle: {
    color: "white",
    padding: "8px 16px",
    borderRadius: "4px",
    fontSize: "12px",
    textAlign: "center",
  },
  visualizationPanel: {
    flex: 1,
    backgroundColor: "#000",
    borderRadius: "8px",
    position: "relative",
    overflow: "hidden",
    minHeight: "500px",
    height: "60vh",
  },
  visualizationTitle: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: "rgba(0,0,0,0.8)",
    color: "white",
    padding: "8px 16px",
    fontSize: "14px",
    fontWeight: "bold",
    zIndex: 1000,
  },
  settingsPanel: {
    flex: 1,
    backgroundColor: "#e5e5e5",
    border: "2px solid #ccc",
    borderRadius: "8px",
    padding: "15px",
    overflow: "visible",
    minHeight: "40vh",
  },
  repairProposalPanel: {
    flex: 1,
    backgroundColor: "#e5e5e5",
    border: "2px solid #ccc",
    borderRadius: "8px",
    padding: "15px",
  },
  proposalContent: {
    borderTop: "1px solid #999",
    paddingTop: "15px",
    backgroundColor: "white",
    padding: "15px",
    borderRadius: "4px",
    border: "1px solid #ccc",
  },
  debugInfo: {
    fontSize: "10px",
    color: "#666",
    marginBottom: "10px",
    padding: "8px",
    backgroundColor: "#f8f9fa",
    borderRadius: "4px",
    border: "1px solid #e9ecef",
  },
  repairArea: {
    marginBottom: "12px",
    padding: "10px",
    backgroundColor: "#ffebee",
    borderRadius: "6px",
    border: "2px solid #ffcdd2",
  },
  summary: {
    marginTop: "15px",
    padding: "12px",
    backgroundColor: "#e3f2fd",
    borderRadius: "6px",
    border: "2px solid #90caf9",
  },
  noRepairs: {
    fontSize: "12px",
    fontStyle: "italic",
    textAlign: "center",
    padding: "20px",
    borderRadius: "6px",
  },
  savedDataPreview: {
    marginBottom: "15px",
    padding: "10px",
    backgroundColor: "#d4edda",
    borderRadius: "4px",
    border: "1px solid #c3e6cb",
  },
  input: {
    width: "100%",
    padding: "6px 8px",
    border: "1px solid #999",
    borderRadius: "4px",
    backgroundColor: "white",
    fontSize: "12px",
  },
  noDataDialog: {
    backgroundColor: "white",
    borderRadius: "8px",
    padding: "24px",
    width: "90%",
    maxWidth: "800px",
    maxHeight: "80%",
    overflow: "auto",
    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.15)",
    position: "relative",
  },
};

export const buttonStyles = {
  screenSwitch: {
    color: "white",
    border: "none",
    borderRadius: "4px",
    padding: "6px 12px",
    cursor: "pointer",
    fontSize: "11px",
    fontWeight: "500",
    position: "relative",
  },
  viewMode: {
    backgroundColor: "#3498db",
    color: "white",
    border: "none",
    borderRadius: "4px",
    padding: "6px 12px",
    cursor: "pointer",
    fontSize: "11px",
    fontWeight: "500",
    marginRight: "5px",
  },
  visualizationMode: {
    backgroundColor: "#666",
    color: "white",
    border: "none",
    borderRadius: "4px",
    padding: "6px 12px",
    cursor: "pointer",
    fontSize: "11px",
    fontWeight: "500",
  },
  increment: {
    backgroundColor: "#666",
    color: "white",
    border: "none",
    borderRadius: "3px",
    padding: "4px 8px",
    cursor: "pointer",
    fontSize: "12px",
  },
  presetCritical: {
    padding: "4px 8px",
    fontSize: "10px",
    backgroundColor: "#DC2626",
    color: "white",
    border: "none",
    borderRadius: "3px",
    cursor: "pointer",
  },
  presetStandard: {
    padding: "4px 8px",
    fontSize: "10px",
    backgroundColor: "#F59E0B",
    color: "white",
    border: "none",
    borderRadius: "3px",
    cursor: "pointer",
  },
  presetConservative: {
    padding: "4px 8px",
    fontSize: "10px",
    backgroundColor: "#10B981",
    color: "white",
    border: "none",
    borderRadius: "3px",
    cursor: "pointer",
  },
  accept: {
    color: "white",
    border: "none",
    borderRadius: "6px",
    padding: "10px 20px",
    cursor: "pointer",
    fontSize: "12px",
    fontWeight: "600",
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
  },
  capture: {
    backgroundColor: "#3b82f6",
    color: "white",
    border: "none",
    borderRadius: "4px",
    padding: "6px 12px",
    cursor: "pointer",
    fontSize: "10px",
    fontWeight: "500",
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "4px",
  },
  export: {
    backgroundColor: "#8b5cf6",
    color: "white",
    border: "none",
    borderRadius: "4px",
    padding: "6px 12px",
    cursor: "pointer",
    fontSize: "10px",
    fontWeight: "500",
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "4px",
  },
  closeDialog: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: "4px",
    borderRadius: "4px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  dialogButton: {
    padding: "8px 16px",
    backgroundColor: "#3182ce",
    color: "white",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "14px",
  },
};

export const textStyles = {
  panelTitle: {
    margin: "0 0 20px 0",
    fontSize: "14px",
    fontWeight: "bold",
    textAlign: "center",
    color: "#333",
  },
  label: {
    display: "block",
    marginBottom: "5px",
    fontSize: "12px",
    fontWeight: "500",
    color: "#333",
  },
  unit: {
    fontSize: "11px",
    color: "#666",
    minWidth: "20px",
  },
  proposalInfo: {
    fontSize: "12px",
    marginBottom: "10px",
    color: "#333",
  },
  repairAreaTitle: {
    fontSize: "14px",
    fontWeight: "bold",
    marginBottom: "6px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    color: "#d32f2f",
  },
  repairAreaBadge: {
    fontSize: "10px",
    backgroundColor: "#ef5350",
    color: "white",
    padding: "2px 6px",
    borderRadius: "10px",
  },
  repairAreaDetails: {
    fontSize: "11px",
    color: "#555",
    marginBottom: "8px",
  },
  repairAreaCost: {
    fontSize: "12px",
    fontWeight: "bold",
    color: "#d32f2f",
  },
  summaryTitle: {
    fontSize: "14px",
    fontWeight: "bold",
    marginBottom: "10px",
    color: "#1565c0",
  },
  summaryDetails: {
    fontSize: "12px",
    color: "#333",
    marginBottom: "10px",
  },
  totalCost: {
    fontSize: "14px",
    fontWeight: "bold",
    color: "#1565c0",
  },
  noRepairsTitle: {
    fontSize: "14px",
    fontWeight: "bold",
    marginBottom: "10px",
  },
  noRepairsContent: {
    fontSize: "12px",
    color: "#666",
  },
  noRepairsSuggestion: {
    fontSize: "11px",
    color: "#d32f2f",
    marginTop: "10px",
  },
  savedDataTitle: {
    fontSize: "12px",
    fontWeight: "bold",
    marginBottom: "5px",
    color: "#2e7d32",
  },
  savedDataContent: {
    fontSize: "11px",
    color: "#555",
  },
  statusMessage: {
    position: "absolute",
    top: "40px",
    left: "16px",
    fontSize: "12px",
    fontWeight: "bold",
    zIndex: 1000,
  },
  dialogTitle: {
    fontSize: "18px",
    fontWeight: "bold",
    margin: "0 0 16px 0",
    color: "#333",
  },
  dialogContent: {
    fontSize: "14px",
    color: "#555",
    lineHeight: "1.5",
  },
};

export const layoutStyles = {
  container: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    padding: "10px",
    height: "100%",
    backgroundColor: "#f5f5f5",
  },
  mainContent: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "8px 16px",
    backgroundColor: "#333",
    color: "white",
    borderRadius: "4px",
    fontSize: "12px",
  },
  visualizationContainer: {
    display: "flex",
    gap: "10px",
    flex: 1,
    minHeight: "60vh",
  },
  controlPanels: {
    display: "flex",
    gap: "10px",
    minHeight: "40vh",
  },
  canvas: {
    width: "100%",
    height: "100%",
    display: "block",
  },
  viewModeToggle: {
    position: "absolute",
    top: "40px",
    right: "16px",
    zIndex: 1000,
  },
  visualizationModeToggle: {
    position: "absolute",
    top: "80px",
    right: "16px",
    zIndex: 1000,
  },
  dataIndicatorDot: {
    width: "8px",
    height: "8px",
    backgroundColor: "#10B981",
    borderRadius: "50%",
    position: "absolute",
    top: "4px",
    right: "4px",
  },
  dataSavedIndicator: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    fontSize: "10px",
    color: "#10B981",
    fontWeight: "bold",
    position: "relative",
  },
  quickActions: {
    display: "flex",
    gap: "8px",
    marginTop: "15px",
  },
  noDataDialogOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2000,
  },
  dialogHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "16px",
  },
};
export default styles;