const styles = {
  container: {
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    backgroundColor: "#1a1a1a",
    fontFamily: "'Roboto', sans-serif",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "10px 20px",
    color: "white",
    height: "60px",
  },
  headerTitle: {
    fontSize: "20px",
    fontWeight: "bold",
  },
  headerControls: {
    display: "flex",
    alignItems: "center",
    gap: "15px",
  },
  folderUpload: {
    display: "inline-block",
  },
  folderLabel: {
    padding: "8px 16px",
    backgroundColor: "#3B82F6",
    color: "white",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "500",
  },
  controls: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  controlLabel: {
    color: "#cccccc",
    fontSize: "14px",
    display: "flex",
    alignItems: "center",
  },
  headerFileList: {
    display: "flex",
    gap: "10px",
    overflowX: "auto",
    maxWidth: "400px",
  },
  headerFileItem: (isSelected) => ({
    padding: "6px 12px",
    backgroundColor: isSelected ? "#3B82F6" : "#2D3748",
    color: "white",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "12px",
    whiteSpace: "nowrap",
  }),
  contentArea: {
    display: "flex",
    flex: 1,
    overflow: "hidden",
  },
  mainContent: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    padding: "20px",
    overflow: "auto",
  },
  visualization: {
    flex: 1,
    position: "relative",
    backgroundColor: "#000000",
    borderRadius: "8px",
    overflow: "hidden",
    marginBottom: "20px",
  },
  canvasContainer: {
    width: "100%",
    height: "100%",
    position: "relative",
  },
  loading: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    color: "white",
    fontSize: "16px",
  },
  noFileMessage: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    color: "#cccccc",
    fontSize: "16px",
    textAlign: "center",
  },
  gradientScale: {
    position: "absolute",
    bottom: "20px",
    left: "20px",
    zIndex: 10,
  },
  thumbnailsContainer: {
    display: "flex",
    gap: "15px",
    overflowX: "auto",
    padding: "10px 0",
  },
  thumbnailItem: (isSelected) => ({
    width: "100px",
    height: "100px",
    position: "relative",
    border: isSelected ? "2px solid #3B82F6" : "2px solid #404040",
    borderRadius: "6px",
    cursor: "pointer",
    overflow: "hidden",
  }),
  thumbnailLabel: {
    position: "absolute",
    bottom: "0",
    left: "0",
    right: "0",
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    color: "white",
    fontSize: "10px",
    padding: "4px",
    textAlign: "center",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
};

export default styles;